[package]
name = "dropshot-rustc-panic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
